Repository anushkaa-dubey/QuickQR, pull requests merged in 2025-02, with the labels that each got.

#82 Matching signup login UI
  index.html
  style.css
Labels: acwoc, easy

#94 Updated the Readme.Md file & Fixes the Major Design Glitch Bug
  README.md
  index.html
  instruction.html
  script.js
  style.css
Labels: bug, documentation, acwoc, medium

#93 added eye button to toggle password visibility
  index.html
Labels: acwoc, easy

#98 added faq section
  faq.css
  faq.html
  index.html
  style.css
Labels: enhancement, acwoc, easy

#100 Tried to Update the Logo and Stlyes
  batch.css
  batch.html
  faq.html
  index.html
  instruction.html
  style.css
Labels: acwoc, easy
