Repository anushkaa-dubey/QuickQR, pull requests merged in 2025-01, with the labels that each got.

#10 Resolved QR Code Download Issue: #3 (issue no. 3)
  index.html
  script.js
  style.css
Labels: acwoc, medium

#13 Made UI more professional
  index.html
  script.js
  style.css
Labels: acwoc, medium

#14 CSS changes
  index.html
  style.css
Labels: acwoc, medium

#27 ✨ Added Scroll Button to the Homepage for Improved Navigation 🚀
  index.html
  script.js
  style.css
Labels: acwoc, medium

#30 Update style.css
  style.css
Labels: acwoc, medium

#33 #20 issue : Successfully Added [NEW FEATURE] Dark Mode Toggle
  index.html
  script.js
  style.css
Labels: acwoc, medium

#35 Updates footer with social links
  index.html
Labels: acwoc, easy

#38 ✅ Fixing the Overlap Issue Between Login and Day/Night Toggle Buttons
  style.css
Labels: acwoc, easy

#41 🔧 Fixed Social Icon Underline and Enhanced Hover Effects
  style.css
Labels: acwoc, easy

#42 instructions page added
  images/img1.png
  images/img2.png
  images/img3.png
  index.html
  instruction.html
  style.css
Labels: acwoc, medium

#46 Share Button & QR Data in a Database (Firebase)
  index.html
  script.js
  share.html
  share.js
  style.css
Labels: acwoc, medium

#52 Fetch and Showing the Generated QR Codes for the Authenticated Users
  index.html
  script.js
  share.js
  style.css
Labels: acwoc, hard

#54 Added Multi-Format Export Feature for the QR Codes
  index.html
  script.js
  share.html
  share.js
  style.css
Labels: acwoc, medium

#56 added tag for toggle button
  index.html
  script.js
  style.css
Labels: acwoc, easy

#58 Fixed the Listed & New Addition Bugs Found in the Project
  index.html
  script.js
  style.css
Labels: acwoc, hard

#67 Scanner Added
  index.html
  script.js
  style.css
Labels: acwoc, medium

#64 🚀 Smooth Scroll to Top Button on the Instructions Page
  instruction.html
Labels: acwoc, easy

#63 enhanced the login page
  index.html
  style.css
Labels: acwoc, easy

#68 Enhanced Footer
  index.html
  style.css
Labels: acwoc, easy

#72 Signup Page added
  index.html
  style.css
Labels: acwoc, medium

#79 Fixed the Mobile Responsiveness and done some Design Improvement
  index.html
  script.js
  style.css
Labels: acwoc, medium

#80 ⬆️ Added Scroll Button to Home Page 🚀
  index.html
  style.css
Labels: acwoc, easy
